<a href="https://colab.research.google.com/github/YugyeongJo/SeSAC_Python_Study/blob/main/docs/06_Python_Basic(Datatype_List2)_0708_0709.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 기초

<목차>
1. 변수
2. 연산자
3. 제어문
4. 함수
5. 자료형 1
6. 자료형 2
7. 정규표현식
8. 판다스
9. 시각화
10. 파일 입출력

<hr>

# 5. 자료형 2

## 튜플(Tuple)
- 소괄호 ()를 이용해 생성
- 읽기 전용, 속도가 빨라 수정이 필요 없는 배열 형태의 데이터 타입에 사용
- 데이터를 수정할 수 없기 때문에 제공되는 함수가 많지 않음
- 튜플의 불변성, 패킹/언패킹 기능, 그리고 여러 값을 하나의 단위로 처리하기 때문에 데이터가 변경되지 않아야 하는 경우(ex. 딕셔너리 키)나 성능이 중요한 경우 튜플을 사용
- 데이터의 무결성을 유지, 복합 키가 필요, 함수에서 여러 값을 반환할 때 특히 유용

In [ ]:
numbers1 = (1, 2, 3, 4, 5)
type(numbers1)

tuple

In [ ]:
numbers2 = (1, )
type(numbers2)

tuple

In [ ]:
numbers_2d = ((1, 2, 3), (4, 5, 6))
numbers_2d

((1, 2, 3), (4, 5, 6))

### 튜플관련 메서드
- 리스트와 튜플은 모두 시퀀스 타입이지만, 리스트는 가변(mutable)이고, 튜플은 불변(immutable) 가능한 메서드의 차이
- 리스트는 다양한 수정 메서드(append, extend, insert, remove, pop, clear, sort, revers 등)를 가짐
- 튜플은 불변이기 때문에 내용을 수정하는 메서드가 없음

|방법|설명|비고|
|--|--|--|
|tupleData = ()|튜플을 만들어 줌||
|len(tupleDate)|튜플의 항목 수를 반환||
|min(tuple), max(tuple)|튜플에서 가장 작은 값(min)과 가장 큰 값(max)을 반환||
|tupleData.count(value)|튜플에서 value의 개수를 반환||
|tupleData.index(value, position)|position 위치 이후에서 value가 있는 인덱스를 반환||

In [ ]:
def calculate_statistics(numbers):
  mean = sum(numbers) / len(numbers)
  variance = sum((x-mean)**2 for x in numbers) / len(numbers)
  return mean, variance

# 튜플로 반환된 값을 함수 인수로 사용
numbers = [1, 2, 3, 4, 5]
mean, variance = calculate_statistics(numbers)
print(f"Mean : {mean}, Variance: {variance}")

Mean : 3.0, Variance: 2.0

In [ ]:
def print_statistics(statistics):
  mean, variance = statistics
  print(f"Mean: {mean}, Variance:{variance}")

# 튜플을 인수로 전달
print_statistics((mean, variance))

Mean: 3.0, Variance:2.0

In [ ]:
# 함수에서 여러 값 반환
def get_user_info():
  return("Alice", 30, "alice@example.com")

name, age, email = get_user_info()
print(f"Name:{name}, Age:{age}, Email:{email}")

Name:Alice, Age:30, Email:alice@example.com

In [ ]:
# 좌표 표현
def calculate_distance(point1, point2):
  return ((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2)**0.5

point_a = (0, 0)
point_b = (3, 4)
distance = calculate_distance(point_a, point_b)
print(f"Distance : {distance}")

Distance : 5.0

In [ ]:
# 딕셔너리의 키로 사용
student_grades = {
    ("John", "Doe"): 85
    , ("Jane", "Smith"): 92
    , ("Bob", "Johnson"): 78
}

print(student_grades[("Jane", "Smith")])

92

In [ ]:
# 네임드 튜플 사용
from collections import namedtuple

Person = namedtuple('Person', ['name', 'age', 'city'])
alice = Person("Alice", 30, "New York")
print(f"{alice.name} is {alice.age} years old and lives in {alice.city}")

# 네임드 튜플 (named tuple)
# Python의 collections 모듈에서 제공하는 클래스 중 하나로, 튜플과 비슷하지만 필드 이름을 가질 수 있는 튜플
# 이를 통해 코드의 가독성을 높이고, 데이터에 의미 있는 이름을 부여할 수 있다.

Alice is 30 years old and lives in New York

In [ ]:
# 고정된 데이터 집합 표현
DAYS_OF_WEEK = ("Mon", "Tues", "Wedn", "Thur", "Fri", "Sat", "Sun")

def is_weekend(day):
  return day in DAYS_OF_WEEK[-2:]

print(is_weekend("Sat"))

True

In [ ]:
# 함수로 인자 전달
def print_person_info(info):
  name, age, occupation = info
  print(f"{name} is {age} years old and works as a {occupation}")

person_info = ("Charlie", 35, "Engineer")
print_person_info(person_info)

Charlie is 35 years old and works as a Engineer

In [ ]:
# 반복 가능한(iterable) 객체의 언패킹
numbers = (1, 2, 3, 4, 5)
first, *middle, last = numbers
print(f"First: {first}, Middle: {middle}, Last: {last}")

# *연산자 : 변수 할당 시 나머지 값들을 하나의 리스트로 모아주는 역할

First: 1, Middle: [2, 3, 4], Last: 5

In [ ]:
# 데이터베이스 레코드 표현
def fetch_user_records():
  return [
      (1, "Alice", "alice@example.com")
      , (2, "Bob", "bob@example.com")
      , (3, "Charlie", "charlie@example.com")
  ]

for user_id, name, email in fetch_user_records():
  print(f"ID: {user_id}, Name: {name}, Email: {email}")

ID: 1, Name: Alice, Email: alice@example.com
ID: 2, Name: Bob, Email: bob@example.com
ID: 3, Name: Charlie, Email: charlie@example.com

In [ ]:
# 상수 집합 정의
HTTP_STATUS_CODES = (200, 201, 204, 400, 401, 403, 404, 500)

def is_success(status_code):
  return status_code in HTTP_STATUS_CODES[:3]

print(is_success(200))

True

In [ ]:
# 다중 할당
def swap(a, b):
  return b, a

x, y = 10, 20
print(f"Before swap : x = {x}, y = {y}")
x, y = swap(x, y)
print(f"After swap : x = {x}, y = {y}")

# swap함수는 두 인수를 받아서 (b, a)형태의 튜플을 반환
# 여러 값을 콤마로 구분하여 한 줄에 대입할 때 암묵적으로 튜플을 사용

Before swap : x = 10, y = 20
After swap : x = 20, y = 10

In [ ]:
# 함수에서 여러 값 반환
import numpy as np
from sklearn.model_selection import train_test_split

# 데이터와 레이블을 튜플로 변환
dataset = (np.random.rand(100, 5), np.random.randint(0, 2, 100))
print(dataset)

(array([[8.86350141e-01, 6.29711410e-01, 6.40702763e-01, 7.12401667e-01,
        6.40920217e-01],
       [6.19469219e-01, 9.87752401e-01, 2.37972070e-01, 8.85385735e-01,
        8.62786616e-01],
       [8.89738934e-01, 3.86863072e-01, 9.02303484e-01, 7.37638247e-01,
        2.14843874e-01],
       [5.22034525e-01, 6.71339958e-01, 8.34783355e-01, 5.55590044e-01,
        8.01942744e-01],
       [3.02383791e-01, 1.52515464e-01, 1.37665916e-01, 8.89481703e-01,
        8.86199417e-01],
       [3.28205957e-01, 7.87256428e-01, 4.35531859e-01, 1.52574349e-01,
        2.95264357e-01],
       [6.36582643e-01, 8.16208422e-01, 8.29003590e-01, 5.81200435e-01,
        6.01840503e-01],
       [2.75269886e-01, 2.32232308e-01, 3.01916466e-01, 6.44895267e-02,
        9.89637678e-01],
       [8.52155268e-01, 5.69431874e-01, 2.02253348e-01, 2.21244473e-01,
        8.57749208e-01],
       [9.54740421e-02, 1.22241255e-01, 9.72612649e-01, 8.89916945e-01,
        3.97141242e-01],
       [9.78957418e-01, 7.46264359e-01, 1.47660190e-01, 2.69970230e-01,
        4.00362750e-01],
       [6.66860011e-01, 2.16579961e-01, 2.20739612e-01, 3.88026673e-01,
        3.16702324e-01],
       [7.73633669e-01, 6.68264019e-01, 3.56463574e-02, 2.77786389e-01,
        4.75750596e-01],
       [7.78125781e-01, 1.22982039e-01, 5.02719559e-01, 1.79915397e-01,
        1.09797064e-01],
       [7.76580613e-01, 3.13732627e-01, 8.10121438e-01, 9.63935484e-01,
        2.29794746e-01],
       [8.13074417e-01, 6.91388484e-01, 5.49352456e-03, 1.97982539e-01,
        8.05955344e-01],
       [9.15076917e-01, 5.13095529e-01, 6.81335913e-02, 9.07368854e-01,
        2.26030984e-01],
       [5.08119344e-01, 9.17987817e-01, 7.39126623e-01, 6.95818026e-01,
        9.40312078e-01],
       [7.23727257e-01, 1.79671983e-01, 2.23454257e-01, 4.51400785e-01,
        2.44414192e-01],
       [1.36764236e-01, 7.66782525e-01, 2.07998322e-01, 7.39298472e-01,
        1.90195820e-01],
       [2.88197094e-01, 1.92134098e-01, 9.63012863e-02, 5.49552093e-01,
        8.47872215e-01],
       [1.61280643e-01, 3.25034664e-01, 4.52179084e-01, 9.00051116e-01,
        3.63696483e-01],
       [9.47091250e-02, 9.16752910e-01, 2.42781870e-01, 2.97463475e-01,
        3.45368413e-01],
       [3.99823181e-01, 4.15033730e-01, 5.13200066e-01, 5.69277565e-01,
        6.02588743e-01],
       [4.04884156e-01, 9.81965508e-02, 2.93296938e-01, 2.02961628e-01,
        4.26463297e-01],
       [6.15430025e-01, 4.73935241e-01, 3.40235562e-01, 8.49700589e-01,
        7.51580923e-01],
       [4.88871522e-01, 6.31502633e-01, 6.36120226e-01, 8.42112178e-01,
        9.77821803e-01],
       [7.35864318e-01, 8.56357287e-01, 5.44825004e-01, 7.06694085e-01,
        9.83541306e-01],
       [7.46562134e-01, 2.18199921e-01, 7.71056663e-01, 7.28866867e-01,
        8.69349625e-02],
       [3.91355866e-01, 8.58300699e-01, 6.21191547e-01, 1.89936330e-01,
        4.21760215e-01],
       [8.52096333e-01, 2.18942588e-01, 5.77662016e-02, 2.92447218e-01,
        6.90422402e-01],
       [8.66516985e-01, 4.92254408e-01, 3.06581483e-01, 2.41220366e-01,
        1.55524484e-01],
       [9.07685846e-01, 2.27306127e-01, 4.68189777e-01, 1.48943687e-02,
        8.42814847e-01],
       [8.38358681e-01, 5.42313553e-01, 5.50133202e-01, 8.66128805e-01,
        4.48216195e-01],
       [1.35932607e-01, 6.63528772e-01, 8.81191656e-01, 7.74258366e-01,
        7.32075255e-01],
       [8.62831546e-01, 1.76476388e-01, 8.66260658e-01, 8.20427229e-01,
        1.79908777e-01],
       [9.45762187e-01, 5.31069393e-01, 6.07454859e-01, 3.41337588e-01,
        7.34162739e-01],
       [3.69224279e-01, 8.21927614e-02, 9.75513559e-01, 8.57992103e-01,
        7.75650141e-01],
       [7.92364661e-01, 5.60482995e-01, 7.98703220e-01, 7.09568929e-01,
        6.12381927e-01],
       [9.63758382e-01, 8.30206793e-01, 9.74689493e-01, 7.98021966e-01,
        8.61226898e-01],
       [3.09300307e-01, 5.29078905e-01, 9.93258156e-01, 6.91801812e-01,
        6.66180477e-02],
       [7.11484882e-01, 9.78599545e-01, 5.00443463e-01, 4.50558663e-02,
        7.52431783e-01],
       [8.21309480e-01, 4.03188316e-01, 3.10704864e-01, 1.77515141e-01,
        6.60659196e-01],
       [4.80293013e-01, 7.09178105e-01, 7.94429820e-02, 5.82266154e-01,
        5.77344336e-02],
       [8.86236766e-03, 4.60756670e-01, 6.06328097e-01, 6.02435423e-01,
        1.39182164e-02],
       [9.79922414e-01, 3.93187138e-01, 8.62861598e-01, 8.85154924e-01,
        2.64050132e-01],
       [5.42632856e-01, 1.14053845e-01, 6.90339914e-01, 2.35438341e-01,
        6.33669832e-01],
       [4.15696587e-01, 1.82201696e-01, 6.08618636e-01, 8.42995541e-01,
        9.37020280e-01],
       [1.45903875e-01, 9.36542030e-01, 3.26092224e-01, 3.27976763e-01,
        1.87537688e-01],
       [2.30549587e-03, 4.91514919e-01, 9.04678188e-01, 4.45007072e-01,
        1.44138986e-01],
       [2.56455786e-01, 8.82946588e-01, 4.29452909e-01, 5.92204147e-01,
        3.44320723e-01],
       [5.54349645e-01, 3.07157040e-01, 8.87526399e-01, 1.59961243e-01,
        7.15451915e-01],
       [1.53342991e-01, 5.75318302e-01, 6.09364190e-01, 9.17571313e-01,
        2.57868107e-01],
       [8.02397766e-02, 3.67051705e-02, 4.54584930e-01, 8.56086114e-01,
        9.50676969e-01],
       [1.89068324e-01, 1.61756196e-01, 7.73214690e-01, 7.77527606e-01,
        9.38258543e-01],
       [1.86393980e-01, 4.57593546e-01, 3.83315795e-01, 3.26628672e-01,
        7.45784685e-01],
       [2.23856691e-01, 6.79234193e-01, 8.28685622e-01, 7.52074721e-02,
        3.29417030e-01],
       [3.87667120e-01, 2.12774160e-01, 2.49605182e-01, 7.96055570e-01,
        7.34014788e-01],
       [4.61465359e-01, 6.69176666e-02, 5.28360968e-01, 3.02232264e-01,
        9.90593997e-02],
       [4.24387730e-01, 8.09459151e-01, 8.08560386e-01, 3.01550512e-01,
        7.82105742e-01],
       [4.32675189e-01, 8.68673419e-01, 8.87895379e-01, 4.67018108e-01,
        3.39188359e-01],
       [2.84205446e-01, 8.73884538e-01, 2.20708307e-01, 1.51528390e-02,
        1.04833013e-01],
       [2.14193919e-03, 7.63478534e-01, 5.71097742e-01, 7.52946938e-01,
        6.35918123e-01],
       [8.64019567e-01, 8.43571659e-02, 4.27372334e-01, 2.28040678e-01,
        3.35877270e-01],
       [7.78613892e-01, 1.19396531e-01, 7.20147629e-02, 1.84946122e-01,
        3.14869357e-01],
       [9.57627049e-01, 6.18546404e-01, 2.79494222e-03, 5.88069592e-01,
        9.29984966e-01],
       [9.84624583e-01, 3.23106047e-01, 2.69060630e-01, 5.05959844e-01,
        2.00892437e-01],
       [5.54889969e-02, 8.77933743e-02, 8.70801349e-01, 2.22521710e-01,
        6.69823458e-01],
       [7.05274088e-01, 2.37180602e-01, 8.90366838e-02, 1.53717030e-01,
        3.35107419e-01],
       [5.30476165e-01, 7.29614094e-01, 4.68482597e-01, 7.40801037e-01,
        7.41969903e-01],
       [1.05495443e-01, 7.61292352e-01, 7.26322322e-01, 9.46047480e-01,
        7.18232808e-01],
       [8.87969453e-01, 9.10318823e-01, 1.16559747e-01, 6.57912168e-01,
        1.64650653e-02],
       [9.97321788e-02, 2.66634511e-01, 2.54175666e-01, 1.25838078e-01,
        1.23781471e-01],
       [8.21623373e-03, 1.60187166e-01, 7.29161597e-01, 5.48656675e-01,
        4.32468905e-01],
       [7.58693643e-01, 2.29180174e-01, 1.23168779e-01, 5.65690072e-01,
        5.32194890e-01],
       [8.92359123e-01, 2.16960694e-02, 8.22587121e-02, 5.40575435e-01,
        4.49827406e-01],
       [9.47770419e-01, 7.47822688e-01, 1.71179167e-02, 6.48786003e-01,
        6.07573074e-01],
       [8.18057215e-01, 8.07372711e-01, 6.47958227e-01, 2.42346814e-01,
        4.09601034e-01],
       [7.46738170e-01, 5.47443816e-01, 7.78589646e-01, 3.96332088e-01,
        2.16693083e-01],
       [9.07742883e-01, 3.95224966e-01, 8.46621057e-02, 2.26826486e-01,
        5.39332658e-01],
       [3.11505155e-01, 3.01200700e-01, 7.04348974e-01, 8.25372169e-02,
        2.75490554e-01],
       [8.67482055e-01, 5.45780836e-01, 3.83409336e-01, 8.14615070e-02,
        6.82127818e-01],
       [5.67049158e-01, 9.73179214e-01, 2.85597389e-01, 1.44827982e-01,
        6.42080273e-01],
       [2.65849481e-02, 1.27086887e-01, 8.75792340e-01, 1.48363391e-01,
        3.99586039e-01],
       [9.74383321e-01, 5.32261140e-01, 5.26598030e-01, 1.42683955e-01,
        7.61595330e-01],
       [5.92514367e-01, 5.92090460e-01, 9.09508617e-01, 5.41802528e-01,
        9.77257337e-01],
       [5.04352768e-01, 5.66724819e-01, 6.24381858e-01, 7.88198131e-02,
        2.06225788e-01],
       [6.49610155e-01, 1.72622437e-01, 3.16379187e-01, 4.27046140e-01,
        2.20427670e-02],
       [5.54107993e-01, 5.36819340e-01, 9.93842486e-01, 3.12497076e-01,
        5.35093058e-01],
       [6.64592791e-01, 8.99028171e-01, 7.23468629e-01, 2.44199394e-01,
        7.66172670e-01],
       [4.15991024e-01, 7.81957523e-01, 6.14359022e-01, 3.97223605e-01,
        4.95034933e-02],
       [4.45715308e-01, 3.87866822e-01, 3.88212998e-01, 6.72520999e-01,
        9.26766585e-01],
       [3.47146771e-01, 6.38994738e-01, 1.21192807e-01, 5.69574174e-01,
        6.74933070e-01],
       [1.76417872e-05, 1.31626090e-01, 5.50468892e-01, 7.37853250e-01,
        6.75067323e-01],
       [8.13345980e-01, 3.83883527e-01, 2.47621784e-01, 8.21636278e-01,
        7.11787883e-01],
       [5.33776913e-01, 4.71292562e-01, 1.25866116e-01, 3.88167391e-01,
        6.24913386e-01],
       [3.40944465e-01, 3.36255260e-01, 8.10014112e-02, 8.01042506e-02,
        8.44366085e-01],
       [7.65425431e-01, 7.72941866e-01, 8.75336867e-01, 7.82930684e-01,
        7.30671880e-01],
       [6.63668429e-01, 8.12025169e-01, 8.58707690e-01, 3.53555867e-01,
        6.85957674e-01],
       [2.97434470e-01, 4.54483528e-01, 3.19042893e-01, 9.32272652e-01,
        3.73985471e-01]]), array([1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0]))

In [ ]:
# 함수에서 여러 값 반환
import numpy as np
from sklearn.model_selection import train_test_split

# 데이터와 레이블을 튜플로 표현
dataset = (np.random.rand(100, 5), np.random.randint(0, 2, 100))
dataset

(array([[0.11706091, 0.48112006, 0.85441938, 0.14766423, 0.75474776],
        [0.43205655, 0.88938965, 0.41964157, 0.69410273, 0.08241277],
        [0.59169204, 0.79951991, 0.93045285, 0.26894864, 0.02606374],
        [0.52658362, 0.87597113, 0.06891299, 0.89143295, 0.50033638],
        [0.7647693 , 0.08854715, 0.40312637, 0.40021574, 0.35150246],
        [0.46883876, 0.88601287, 0.50646334, 0.266342  , 0.45572421],
        [0.99291815, 0.0391249 , 0.97257496, 0.5740888 , 0.66275054],
        [0.76502653, 0.61802121, 0.25213353, 0.68444509, 0.3781359 ],
        [0.79757372, 0.73991236, 0.60246612, 0.78891578, 0.92728558],
        [0.57952659, 0.72486368, 0.35598218, 0.51495874, 0.53756811],
        [0.83290123, 0.97407325, 0.69396298, 0.51545644, 0.97243293],
        [0.77960272, 0.85929466, 0.8354576 , 0.90142985, 0.20653094],
        [0.29808408, 0.66695628, 0.06449495, 0.37526076, 0.20449233],
        [0.35253131, 0.87319605, 0.75930477, 0.02078422, 0.69502882],
        [0.65045353, 0.32498112, 0.17161276, 0.94919118, 0.29507754],
        [0.15631691, 0.72062753, 0.89476031, 0.24390668, 0.29968198],
        [0.08372615, 0.89927064, 0.81171318, 0.35445656, 0.8762236 ],
        [0.69983377, 0.57848291, 0.2201968 , 0.6192072 , 0.29624977],
        [0.85848519, 0.64667249, 0.51640408, 0.02518794, 0.468741  ],
        [0.87048152, 0.0548598 , 0.79184715, 0.77617224, 0.55338042],
        [0.33149532, 0.23628495, 0.74458435, 0.50319071, 0.00833962],
        [0.57812648, 0.62430717, 0.53192122, 0.78468999, 0.51888754],
        [0.86983169, 0.18251904, 0.33152155, 0.17782406, 0.72437493],
        [0.58867133, 0.82298321, 0.43194677, 0.04114803, 0.07299829],
        [0.29013538, 0.13464253, 0.62350573, 0.69918952, 0.45003256],
        [0.20582676, 0.25409044, 0.77645609, 0.8397219 , 0.96279516],
        [0.40955345, 0.63000149, 0.03097265, 0.38215803, 0.65246439],
        [0.35778388, 0.63448107, 0.4203955 , 0.51877904, 0.6130321 ],
        [0.35488301, 0.33273577, 0.2461811 , 0.42089258, 0.48465108],
        [0.96720851, 0.12684583, 0.5743883 , 0.76274232, 0.70961973],
        [0.33101976, 0.41205221, 0.20144452, 0.40720422, 0.57780696],
        [0.32555332, 0.20733849, 0.11198951, 0.08097252, 0.620844  ],
        [0.96641864, 0.94748737, 0.54299577, 0.12496054, 0.89866761],
        [0.25245238, 0.52955247, 0.95835763, 0.66655118, 0.53114974],
        [0.463257  , 0.42119116, 0.10824525, 0.96172028, 0.44639317],
        [0.35102599, 0.35830118, 0.54897449, 0.04407833, 0.22438658],
        [0.97715072, 0.44607655, 0.73045864, 0.69919309, 0.9677263 ],
        [0.4350844 , 0.09183441, 0.0993385 , 0.40121708, 0.00261065],
        [0.76851834, 0.55542098, 0.9537054 , 0.5305746 , 0.17716838],
        [0.72131475, 0.17813768, 0.3526746 , 0.18980225, 0.24149446],
        [0.21400473, 0.9891533 , 0.3516935 , 0.77935841, 0.12581536],
        [0.24867846, 0.50851012, 0.25237422, 0.27538397, 0.95092706],
        [0.52435709, 0.44542813, 0.20676708, 0.56808432, 0.27952911],
        [0.60500894, 0.27001787, 0.27927658, 0.13492479, 0.95746061],
        [0.16991699, 0.69567016, 0.72984542, 0.26114724, 0.215369  ],
        [0.85456555, 0.3516105 , 0.74722427, 0.62880391, 0.06093921],
        [0.387388  , 0.77710752, 0.09685518, 0.95435716, 0.90494615],
        [0.64902194, 0.6590659 , 0.2101103 , 0.52673139, 0.04354315],
        [0.47813051, 0.08160169, 0.94996426, 0.63639214, 0.23186377],
        [0.84170428, 0.79087197, 0.03866054, 0.87340112, 0.54046761],
        [0.35885672, 0.27390566, 0.42539069, 0.81483886, 0.65064974],
        [0.95353205, 0.24379232, 0.52198761, 0.75464959, 0.48506395],
        [0.12854458, 0.12776813, 0.32974849, 0.95622396, 0.15288714],
        [0.10658722, 0.53490594, 0.60261661, 0.48060507, 0.84096831],
        [0.72652435, 0.8090295 , 0.12807242, 0.65917476, 0.52026333],
        [0.44186985, 0.46162089, 0.35032627, 0.78825632, 0.31284966],
        [0.06110076, 0.90387033, 0.98562309, 0.15174471, 0.52693049],
        [0.85068368, 0.16684284, 0.54963513, 0.21105881, 0.03829031],
        [0.620531  , 0.38065379, 0.77427733, 0.50975184, 0.15332728],
        [0.2555208 , 0.60390181, 0.38436174, 0.71982563, 0.1199757 ],
        [0.02161822, 0.36362209, 0.54696108, 0.81983147, 0.81751698],
        [0.3481048 , 0.19220886, 0.2826081 , 0.56416456, 0.73928915],
        [0.69451122, 0.60721271, 0.15122726, 0.22583249, 0.62258445],
        [0.69808437, 0.90257629, 0.30914164, 0.50145587, 0.85745684],
        [0.58412548, 0.36625773, 0.11198062, 0.15640843, 0.21731447],
        [0.78150966, 0.37269797, 0.86619724, 0.26498964, 0.64404512],
        [0.81687382, 0.82299713, 0.87427548, 0.64001761, 0.42177987],
        [0.32858058, 0.36168648, 0.51907751, 0.0819723 , 0.18794641],
        [0.8552817 , 0.59669254, 0.49364739, 0.95914445, 0.7516316 ],
        [0.423278  , 0.18677498, 0.54650892, 0.83182961, 0.68927974],
        [0.27260565, 0.23099918, 0.93021369, 0.81186635, 0.56355235],
        [0.24546827, 0.8701747 , 0.08019599, 0.04599006, 0.53145128],
        [0.51960298, 0.13087363, 0.83527096, 0.31367332, 0.49469049],
        [0.24131376, 0.33653217, 0.99799092, 0.01005596, 0.84238713],
        [0.99044088, 0.19451883, 0.800441  , 0.75789247, 0.82264022],
        [0.58581647, 0.19102083, 0.48827634, 0.63774917, 0.03430309],
        [0.74835765, 0.71143499, 0.21516853, 0.02598551, 0.58503012],
        [0.02037408, 0.37821319, 0.48673502, 0.49773069, 0.5549303 ],
        [0.21320172, 0.79172673, 0.39064641, 0.98162076, 0.12234987],
        [0.690521  , 0.660256  , 0.88323416, 0.04649464, 0.06988907],
        [0.96593897, 0.32121728, 0.34262076, 0.95254415, 0.10789317],
        [0.91596701, 0.1395209 , 0.90855023, 0.86785101, 0.62822948],
        [0.11478825, 0.47703247, 0.01314666, 0.48498118, 0.06035439],
        [0.58015892, 0.65288692, 0.16497086, 0.2801931 , 0.9972294 ],
        [0.51698216, 0.6660811 , 0.70699382, 0.38137586, 0.97448457],
        [0.39969321, 0.24901406, 0.55924577, 0.64906348, 0.84778096],
        [0.72940811, 0.99251305, 0.61126616, 0.94045526, 0.20556649],
        [0.50649686, 0.43503424, 0.98136699, 0.25743717, 0.23781648],
        [0.5279427 , 0.08320886, 0.72674175, 0.61979041, 0.31513028],
        [0.93727784, 0.93519814, 0.46000288, 0.02964108, 0.93877311],
        [0.07566714, 0.51005741, 0.89412325, 0.8806161 , 0.75044627],
        [0.54527005, 0.84410389, 0.67794206, 0.95548069, 0.40500853],
        [0.34070577, 0.63255375, 0.51979973, 0.19829964, 0.35166119],
        [0.59563504, 0.72223052, 0.94561874, 0.48392131, 0.46229893],
        [0.53728064, 0.48911331, 0.94368244, 0.92948031, 0.42975095],
        [0.7936302 , 0.33772643, 0.32761996, 0.52278028, 0.7152545 ],
        [0.5280838 , 0.47578523, 0.51675611, 0.26355687, 0.11947062],
        [0.02933971, 0.57387132, 0.39511033, 0.99606006, 0.93021467],
        [0.39447568, 0.40052726, 0.92484544, 0.12901917, 0.61026961],
        [0.08481578, 0.6225757 , 0.17355659, 0.5115646 , 0.70403084]]),
 array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0]))

In [ ]:
# 파라미터 범위 정의
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# 튜플을 사용하여 파라미터 범위 정의
param_grid = {
    'C' : (0.1, 1, 10)
    , 'kernel' : ('linear', 'rbf')
    , "gamma" : ('scale', 'auto')
}

In [ ]:
# 딕셔너리의 키로 사용
coordinates = {
    (0, 0): "Origin"
    , (1, 2): "Point A"
    , (3, 4): "Point B"
    }
# 특정 좌표의 값을 가져오기
print(coordinates[(1, 2)])

Point A

In [ ]:
# 머신 러닝 사용 사례
import tensorflow as tf

# 예제 데이터
features = [[1, 2], [3, 4], [5, 6]]
labels = [0, 1, 2]

# 튜플을 사용하여 데이터셋 생성
dataset = tf.data.Dataset.from_tensor_slices((features, labels))

for element in dataset:
  print(element)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

## 딕셔너리(Dictionary)
- 중괄호 {}를 이용해서 딕셔너리 생성. 키(key)와 값(value)의 쌍으로 구성된 자료 구조
- 키는 유일(unique)해야 하며, 키에 리스트를 사용할 수 없음. but, 튜플 타입은 사용 가능
- 값은 중복이 가능하며, 모든 타입이 가능
- 키 목록에 없는 데이터를 사용하여 참조하면 에러가 발생, 인덱스를 이용한 참조는 지원안함
- 관계형 데이터를 다룰 때 특히 유용

|방법|설명|비고|
|--|--|--|
|dictData = {"key":"value", ...}|딕셔너리 생성||
|len(dictData)|딕셔너리 항목의 수를 반환||
|dictData.items()|딕셔너리의 각 항목들을(key, value) 형식의 튜플들로 반환||
|dictData.keys()|딕셔너리의 키(key)들을 반환||
|dictData.values()|딕셔너리의 value들을 반환||

In [ ]:
# 새로운 키-값 쌍 추가(insert) : 키를 지정하고 값을 추가로 입력
my_dict = {'apple':1, 'banana': 2}
my_dict['cherry'] = 3
print(my_dict)

{'apple': 1, 'banana': 2, 'cherry': 3}

In [ ]:
# 기존 키의 값 변경 : 키를 지정하여 기존의 값을 변경
my_dict = {'apple':1, 'banana': 2}
my_dict['apple'] = 5
print(my_dict)

{'apple': 5, 'banana': 2}

In [ ]:
# 여러 개의 새로운 키-값 상 추가(update) : 키와 값을 함께 추가로 입력 (update)
my_dict = {'apple':1, 'banana': 2}
my_dict.update({'cherry': 3, 'date': 4})
print(my_dict)

{'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}

In [ ]:
# 여러 개 기존 값의 값 update() : 키 값을 지정하여 기존의 값을 변경
my_dict = {'apple':1, 'banana': 2}
my_dict.update({'apple': 5, 'banana': 6})
print(my_dict)

{'apple': 5, 'banana': 6}

In [ ]:
# 기존 데이터의 삭제(del()) : 키 값으로 지정하여 key와 value를 삭제
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
del my_dict['banana']
print(my_dict)

{'apple': 1, 'cherry': 3}

In [ ]:
# 기존 데이터의 삭제(pop(키 지정)) : 키 값으로 지정하여 키와 값을 삭제하고, 삭제 항목을 리턴값으로 받음
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
removed_value = my_dict.pop('banana')
print(my_dict)
print(removed_value)

{'apple': 1, 'cherry': 3}
2

In [ ]:
# popitem() : 마지막 자료 삭제, 삭제 항목(key와 value값)을 리턴 값으로 받은
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
last_item = my_dict.popitem()
print(my_dict)
print(last_item)

{'apple': 1, 'banana': 2}
('cherry', 3)

In [ ]:
dictionary = {'a':1, 'b':2, 'c':3}
value1 = dictionary.pop('b')
print("Value 1: ", value1)

value2 = dictionary.pop('d', 'default')
print("Value : 2", value2)

Value 1:  2
Value : 2 default

In [ ]:
dictionary = {'a':1, 'b':2, 'c':3}
item = dictionary.popitem()
print("Item : ", item)

Item :  ('c', 3)

In [ ]:
# clear()
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
my_dict.clear()
print(my_dict)

{}

In [ ]:
example_dict = {'name': 'Alice', 'age': 25, 'city': 'Seoul'}

# items() 메서드 사용
print("Items:")
for key, value in example_dict.items():
  print(f"Key: {key}, Value: {value}")

# keys() 메서드 사용
print("\nKeys:")
for key in example_dict.keys():
  print(f"Key: {key}")

# values() 메서드 사용
print("\nValues:")
for value in example_dict.values():
  print(f"Value: {value}")

Items:
Key: name, Value: Alice
Key: age, Value: 25
Key: city, Value: Seoul

Keys:
Key: name
Key: age
Key: city

Values:
Value: Alice
Value: 25
Value: Seoul

In [ ]:
# 사용자 정보 저장 및 접근
user = {
    "name":"Alice"
    , "age": 30
    , "email": "alice@example.com"
    , "is_active": True
}

print(f"{user['name']} is {user['age']} years old.")

Alice is 30 years old.

In [ ]:
# 빈도수 계산
words = ["apple", "banana", "apple", "cherry", "banana", "date"]
frequency = {}

for word in words:
  frequency[word] = frequency.get(word, 0) + 1

print(frequency)

{'apple': 2, 'banana': 2, 'cherry': 1, 'date': 1}

In [ ]:
# 설정 관리
settings = {
    "theme":"dark"
    , "font_size": 14
    , "notifications": True
}

if settings["notifications"]:
  print(f"Notifications are enabled. Font size : {settings['font_size']}")

Notifications are enabled. Font size : 14

In [ ]:
# 제이슨 데이터 처리
import json

json_str = '{"name": "Bob", "age": 25, "city": "New York"}'
data = json.loads(json_str)

print(f"{data['name']} lives in {data['city']}")

Bob lives in New York

In [ ]:
# 명령어 매핑
def greet():
  print("Hello!")

def quit_program():
  print("Goodbye!")
  exit()

commands = {
    "hello": greet,
    "quit" : quit_program
}

while True:
  cmd = input("Enter a command: ").lower()
  if cmd in commands:
    commands[cmd]()
  else:
    print("Unknown command")

Enter a command: hell
Unknown command
Enter a command: hello
Hello!
Enter a command: greet
Unknown command
Enter a command: quit
Goodbye!
Enter a command: d
Unknown command

KeyboardInterrupt: Interrupted by user

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 샘플 데이터 생성
data = {
    'color': ['red', 'green', 'blue', 'green', 'red']
    , 'size' : ['S', 'M', 'L', 'M', 'S']
    , 'price' : [10, 20, 30, 20, 10]
    , 'label' : [0, 1, 0, 1, 0]
}

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# 데이터 로드
iris = load_iris()
x, y, = iris.data, iris.target

# 하이퍼파라미터 설정
param_grid = {
    'n_estimators':[10, 50, 100]
    ,'max_depth':[None, 10, 20, 30]
    , 'min_samples_split':[2, 5, 10]
}

In [ ]:
# 학생 성적 관리
student_data = {
    "Alice" : {
        "scores":[85, 90, 88]
        , "id": (123, "A")
    }
    , "Bob": {
        "scores":[78, 82, 79]
        , "id":(124, "B")
    }
    , "Charlie": {
        "scores": [92, 95, 91]
        , "id":(125, "C")
    }
}

# 학생 성적 추가
student_data["Alice"]["scores"].append(95)

# 특정 학생의 데이터 접근
print(student_data["Alice"]["scores"])

[85, 90, 88, 95]

## 집합(set)
- 중괄호 {}를 이용하여 정의, 순서가 정해지지 않고, 중복을 허용하지 않는 집합
- set() 함수는 리스트, 튜플, 딕셔너리를 셋으로 바꿈. 딕셔너리는 키(key)만 셋에 추가됨.
- 집합 연산자(& : 교집합, | : 합집합, - : 차집합) 사용 가능
- 저장한 순서대로 각 요소들이 저장되지 않으며, 중복을 허용 안함.
- True와 1은 같은 값으로 간주되며, False와 0도 같은 값으로 간주됨

In [1]:
fruits = {"apple", "orange", "banana", "apple", "pear"}
type(fruits)

set

In [2]:
fruits

{'apple', 'banana', 'orange', 'pear'}

### 집합 crud
- add()
  + 단일 요소를 집합에 추가할 때 사용
  + 기본 자료형과 튜플 추가함.
  + 리스트와 딕셔너리는 add()함수로 추가할 수 없음
  + 한 번에 하나의 요소만 추가 가능
  + 원본 집합을 직접 수정(반환값 없음.)
  ```
  my_set.add(element)
  ```
- update()
  + 기존 집합에 새로운 요소들을 추가할 때 사용
  + 리스트, 튜플, 딕셔너리, 문자를 추가함.
  + 딕셔너리는 키만 추가됨.
  + 여러 요소를 한번에 추가.
  + 중복된 요소는 자동으로 무시
  + 원본 집합을 직접 수정(반환값 없음.)
  ```
  existing_set.update(iterable)
  ```
- remove()
  + 특정 요소를 제거할 때 사용
  + 요소를 삭제함.
  + 함수의 인수는 셋에서 삭제할 값을 입력
  + 지정한 요소가 집합에 있으면 제거
  + 지정한 요소가 집합에 없으면 KeyError를 발생
  + 원본 집합을 직접 수정(반환값 없음.)
  ```
  my_set.remove(element)
  ```

In [3]:
fruits.add("apple")
fruits

{'apple', 'banana', 'orange', 'pear'}

In [4]:
fruits.add("mango")
fruits

{'apple', 'banana', 'mango', 'orange', 'pear'}

In [5]:
# update()
fruits = {'apple', 'banana', 'cherry'}
fruits.update(['orange', 'mango', 'apple'])
print(fruits)

{'cherry', 'apple', 'banana', 'orange', 'mango'}

In [6]:
# add()
fruits = {'apple', 'banana', 'cherry'}
fruits.add('orange')
print(fruits)

{'cherry', 'apple', 'banana', 'orange'}

In [7]:
# remove()
fruits = {'apple', 'banana', 'cherry'}
fruits.remove('banana')
print(fruits)

{'cherry', 'apple'}

In [8]:
# 중복 요소 제거
data = [1, 2, 2, 3, 4, 4, 5]

# 집합을 사용하여 중복 제거
unique_data = list(set(data))
print(unique_data)

[1, 2, 3, 4, 5]

In [9]:
# 교집합, 합집합, 차집합 연산
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

# 교집합
intersection = set_a & set_b
intersection

{3, 4}

In [10]:
# 합집합
union = set_a | set_b
union

{1, 2, 3, 4, 5, 6}

In [12]:
# 차집합
difference = set_a - set_b
difference

{1, 2}

In [13]:
# 원소의 존재 여부 확인
elements = {1, 2, 3, 4, 5}

print(3 in elements)

True

In [14]:
# 리스트의 고유 요소 추출
words = ["apple", "banana", "apple", "orange", "banana", "apple"]

unique_words = set(words)
unique_words

{'apple', 'banana', 'orange'}

In [15]:
# 여러 조건을 만족하는 데이터 필터링
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

# 두 집합에 모두 포함된 원소
common_elements = set_a & set_b
common_elements

{4, 5}

In [16]:
# 한 집합에만 포함된 원소
unique_elements = set_a ^ set_b
unique_elements

{1, 2, 3, 6, 7, 8}

In [17]:
# 훈련 및 테스트 테이터셋에서 고유값 비교
train_labels = ["cat", "dog", "bird"]
test_labels = ["dog", "fish", "cat"]

# 훈련 및 테스트 데이터의 고유값 추출
train_set = set(train_labels)
test_set = set(test_labels)

# 교집합을 사용하여 공통된 고유값 찾지
common_labels = train_set & test_set
common_labels

{'cat', 'dog'}

In [18]:
# 피처 엔지니어링에서 고유 단어 추출
documents = [
    "the cat in the hat"
    , "the quick brown fox"
    , "jumped over the lazy dog"
]

# 고유 단어 추출
unique_words = set()
for doc in documents:
  words = doc.split()
  unique_words.update(words)

unique_words

{'brown',
 'cat',
 'dog',
 'fox',
 'hat',
 'in',
 'jumped',
 'lazy',
 'over',
 'quick',
 'the'}

## mutable(가변) vs immutable(불변)
- 가변 자료구조(mutable)
  + 생성 후 내용을 변경할 수 있음
  + 메모리 주소가 변경되지 않음
  + ex) 리스트(list), 딕셔너리(dictionary), 집합(set)
- 분변 자료구조 (immutable)
  + 생성 후 내용을 변경할 수 없음
  + 내용 변경 시 새로운 객체가 생성
  + ex) 튜플(tuple), 문자열(str), 정수(int), 실수(float)

In [19]:
# 리스트(mutable)
list_a = [1, 2, 3]
list_b = list_a
list_b.append(4)
list_a

[1, 2, 3, 4]

In [20]:
# 튜플
tuple_a = (1, 2, 3)
tuple_b = tuple_a
tuple_b.append(4)

AttributeError: 'tuple' object has no attribute 'append'

In [21]:
tuple_b = tuple_b + (4, )
print(tuple_a)
print(tuple_b)

(1, 2, 3)
(1, 2, 3, 4)

In [22]:
# 얕은 복사와 깊은 복사에서 변경 가능
# 데이터 타입의 복사 방식에 따라 결과가 달라질 수 있다
import copy

# 얕은 복사 (shallow copy)
list_a = [[1, 2], [3, 4]]
list_b = list_a.copy()
list_b[0][0] = 9
print(list_a)
print(list_b)

[[9, 2], [3, 4]]
[[9, 2], [3, 4]]

In [23]:
# 깊은 복사 (deep copy)
list_c = [[1, 2], [3, 4]]
list_d = copy.deepcopy(list_c)
list_d[0][0] = 9
print(list_c)
print(list_d)

# copy()는 shallow copy 를 생성
# 즉, 새로운 객체를 만들지만 내부 객체에 대한 참조는 그대로 유지

# deepcopy()는 deep copy 를 생성
# 즉, 새로운 객체를 만들고 내부 객체도 모두 새로 생

[[1, 2], [3, 4]]
[[9, 2], [3, 4]]

## iterable (반복가능)
- 파이썬에서 순회할 수 있는 객체
- 요소를 하나씩 반환할 수 있는 객체
- for 루프에서 사용할 수 있음
- 리스트(list), 튜플(tuple), 문자열(str), 딕셔너리(dictionary), 집합(set), range 객체

In [24]:
# 리스트를 이용한 예시
my_list = [1, 2, 3, 4, 5]
for item in my_list:
  print(item, end='')
print()

12345

In [25]:
# 문자열을 이용한 예시
my_string = "Hello"
for char in my_string:
  print(char, end='')
print()

Hello

In [26]:
# range 객체를 이용한 예시
for num in range(5):
  print(num, end='')
print()

01234

In [27]:
# 딕셔너리를 이용한 예시
my_dict = {'a':1, 'b':2, 'c':3}
for key in my_dict:
  print(f"{key}:{my_dict[key]}", end='')
print()

a:1b:2c:3

In [28]:
# iterable 객체를 list()로 변환
print(list("Python"))

['P', 'y', 't', 'h', 'o', 'n']

In [29]:
# 사용자 정의 iterable 사용
for num in CountDown(5):
  print(num, end='')
print()

NameError: name 'CountDown' is not defined

## enumerate ()
- 반복 가능한 객체(iterable)를 인덱스와 함께 튜플 형태로 반환
- 반복문을 사용할 때 인덱스를 쉽게 접근 가능
- range() 함수를 이용해서 반복문의 인덱스를 만든 후 이를 이용해서 인덱스와 리스트 데이터를 처리하는 것은 직관적이지 못하고 코드가 어려워짐.
- 반복자(iterator) 또는 순서(sequence) 객체를 인수로 받음
- enumerate(iter)는 iter 객체를 (0, iter[0]), (1, iter[1]), (2, iter[2]), ... 형식으로 반환

In [30]:
fruits = ['watermelon', 'orange', 'mango', 'grape', 'banana', 'apple']
for fruit in fruits:
  print("데이터는 {}입니다.".format(fruit))

데이터는 watermelon입니다.
데이터는 orange입니다.
데이터는 mango입니다.
데이터는 grape입니다.
데이터는 banana입니다.
데이터는 apple입니다.

In [31]:
for i in range(len(fruits)):
  print("{}번째 데이터는 {}입니다.".format(i+1, fruits[i]))

1번째 데이터는 watermelon입니다.
2번째 데이터는 orange입니다.
3번째 데이터는 mango입니다.
4번째 데이터는 grape입니다.
5번째 데이터는 banana입니다.
6번째 데이터는 apple입니다.

In [32]:
fruits = ['watermelon', 'orange', 'mango', 'grape', 'banana', 'apple']
for index, value in enumerate(fruits):
  print("{}번째 데이터는 {}입니다.".format(index+1, value))

1번째 데이터는 watermelon입니다.
2번째 데이터는 orange입니다.
3번째 데이터는 mango입니다.
4번째 데이터는 grape입니다.
5번째 데이터는 banana입니다.
6번째 데이터는 apple입니다.

In [33]:
data = ['cat', 'dog', 'bird', 'fist']

for idx, value in enumerate(data):
  print(f"Index: {idx}, Value: {value}")

Index: 0, Value: cat
Index: 1, Value: dog
Index: 2, Value: bird
Index: 3, Value: fist

In [34]:
# 가상의 학습 손실 값
losses = [0.9, 0.7, 0.5, 0.3]

# enumerate()를 사용하여 에포크와 손실 값을 출력
for epoch, loss in enumerate(losses):
  print(f"Epoch: {epoch}, Loss: {loss}")

Epoch: 0, Loss: 0.9
Epoch: 1, Loss: 0.7
Epoch: 2, Loss: 0.5
Epoch: 3, Loss: 0.3

In [35]:
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits, start=1):
  print(f"Index: {index}, Fruit: {fruit}")

Index: 1, Fruit: apple
Index: 2, Fruit: banana
Index: 3, Fruit: cherry

In [37]:
# list comprehension 와 함께 사용
fruits = ['apple', 'banana', 'cherry']
indexed_fruits = [(index, fruit) for index, fruit in enumerate(fruits)]

indexed_fruits

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]

In [38]:
# 딕셔너리로 변환
fruits = ['apple', 'banana', 'cherry']
fruit_dict = {index: fruit for index, fruit in enumerate(fruits)}
fruit_dict

{0: 'apple', 1: 'banana', 2: 'cherry'}

In [39]:
# 문자열에서 문자와 인덱스 출력
text = "hello"

for index, char in enumerate(text):
  print(f"Index: {index}, Character: {char}")

Index: 0, Character: h
Index: 1, Character: e
Index: 2, Character: l
Index: 3, Character: l
Index: 4, Character: o

In [42]:
# 문자열 형태의 특성을 숫자로 인코딩할 때 enumerate()를 사용하여 각 문자에 고유한 숫자 인덱스를 부여
from sklearn.preprocessing import LabelEncoder

labels = ['apple', 'banana', 'cherry']
encoder = LabelEncoder()
encoded_laberls = encoder.fit_transform(labels)

print(list(enumerate(encoder.classes_)))

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]

In [45]:
# 모델 평가 시 enumerate()를 사용하여 각 샘플의 인덱스와 예측 결과를 매칭할 수 있음.
# 이를 통해 모델의 성능을 샘플 단위로 분석하거나, 오분류된 샘플을 확인 가능

from sklearn.metrics import accuracy_score

y_true = [0, 1, 0, 1, 0]
y_pred = [0, 0, 1, 2, 0]

for idx, (true, pred) in enumerate(zip(y_true, y_pred)):
  print(f"Sample {idx}: True={true}, Pred={pred}")

print(f"Overall accuracy: {accuracy_score(y_true, y_pred):.2f}")

Sample 0: True=0, Pred=0
Sample 1: True=1, Pred=0
Sample 2: True=0, Pred=1
Sample 3: True=1, Pred=2
Sample 4: True=0, Pred=0
Overall accuracy: 0.40